

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '@/components/header'


export type PageProps = {
  params: { lng: string }
}
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function PageLayout({
  children,
  params: {
    lng
  }
}: {
  children: React.ReactNode,
  params: {lng: string}
}) {

  return (
   <main>
      <Header lng={lng} />
      {children}
   </main>
  )
}
